### ISSUE TITLE
Неподдерживаемые ссылки | Unavailable links

### ISSUE THREAD

**Issue by blueundefined** [tailsjs/SharaAction#1]
**Описание ошибки**
- Ссылочки то не поддерживаются

**Воспроизведение ошибки**
Шаги воспроизведения:

- Перейти по ссылкам на апи

**Ожидаемое поведение**
Открыть ссылочку

**Comment by tailsjs** [comment]
И в правду. Старый домен истёк, ща поменяю.

**Comment by tailsjs** [comment]
Fixed in [7dabf5d](https://github.com/tailsjs/SharaAction/commit/7dabf5df06ec04c89b08dc9847143bbaba612e31)
